### ISSUE TITLE
Angular OnlyOffice Implementation

### ISSUE THREAD

**Issue by steve-njuguna-k** [ONLYOFFICE/document-editor-angular-workspace#20]
Hey, I want to implement OnlyOffice into my Angular project but there seems to be no complete implementation on how to use this repo in an application. As the authors, could you please provide me with a well-documented step-by-step implementation guide, either here in the ReadMe or a blog post. Please. Thank you.

**Comment by justmatt25** [comment]
There seems to be some documentation here: https://www.npmjs.com/package/@onlyoffice/document-editor-angular but thus far I have been unsuccessful in getting it to work in my project.

**Comment by LinneyS** [comment]
Documentation is here
https://github.com/ONLYOFFICE/document-editor-angular-workspace/blob/master/projects/onlyoffice/document-editor-angular/README.md

or here
https://api.onlyoffice.com/editors/angular
